services:
  redpanda:
    image: redpandadata/redpanda:v25.3.9
    container_name: redpanda
    command:
      - redpanda
      - start
      - --smp
      - '1'
      - --reserve-memory
      - 0M
      - --overprovisioned
      - --node-id
      - '1'
      - --kafka-addr
      - PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      - --advertise-kafka-addr
      - PLAINTEXT://redpanda:29092,OUTSIDE://localhost:9092
      - --pandaproxy-addr
      - PLAINTEXT://0.0.0.0:28082,OUTSIDE://0.0.0.0:8082
      - --advertise-pandaproxy-addr
      - PLAINTEXT://redpanda:28082,OUTSIDE://localhost:8082
      - --rpc-addr
      - 0.0.0.0:33145
      - --advertise-rpc-addr
      - redpanda:33145
    ports:
      - 8082:8082
      - 9092:9092
      - 28082:28082
      - 29092:29092

  redpanda-init:
    image: redpandadata/redpanda:v25.3.9
    depends_on:
      - redpanda
    entrypoint: >
      /bin/sh -c "sleep 5 &&
      rpk topic create ais_data --brokers redpanda:29092"

  clickhouse:
    image: clickhouse/clickhouse-server:26.2.14.5
    container_name: clickhouse
    restart: unless-stopped
    depends_on:
      - redpanda-init
    ports:
      - 8123:8123  # HTTP interface
      - 9000:9000  # Native client interface
    volumes:
      - ./clickhouse/initdb:/docker-entrypoint-initdb.d
      - clickhouse-data:/var/lib/clickhouse
    environment:
      - CLICKHOUSE_DB=ais_db
      - CLICKHOUSE_USER=${CLICKHOUSE_USER}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
  
  postgres:
    image: postgres:18
    container_name: airflow_postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=airflow
    volumes:
      - postgres-data:/var/lib/postgresql
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 5s
      retries: 5

  airflow:
    build:
      context: ./airflow
      dockerfile: Dockerfile
    container_name: airflow
    depends_on:
      postgres:
        condition: service_healthy
      clickhouse:
        condition: service_started
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/airflow
      - AIRFLOW__CORE__LOAD_EXAMPLES=false
      - AIRFLOW__CORE__AUTH_MANAGER=airflow.providers.fab.auth_manager.fab_auth_manager.FabAuthManager
      - AIRFLOW_ADMIN_USERNAME=${AIRFLOW_ADMIN_USERNAME}
      - AIRFLOW_ADMIN_PASSWORD=${AIRFLOW_ADMIN_PASSWORD}
      - AIRFLOW_ADMIN_FIRSTNAME=${AIRFLOW_ADMIN_FIRSTNAME}
      - AIRFLOW_ADMIN_LASTNAME=${AIRFLOW_ADMIN_LASTNAME}
      - AIRFLOW_ADMIN_EMAIL=${AIRFLOW_ADMIN_EMAIL}
      - AIRFLOW_CONN_CLICKHOUSE_DEFAULT=clickhouse://${CLICKHOUSE_USER}:${CLICKHOUSE_PASSWORD}@clickhouse:9000/ais_db
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./ais_transformations:/opt/airflow/dbt
      - ./airflow/entrypoint.sh:/opt/airflow/entrypoint.sh
    ports:
      - 8080:8080
    command: bash /opt/airflow/entrypoint.sh
  
  grafana:
    image: grafana/grafana:13.0.1
    container_name: grafana
    depends_on:
      - clickhouse
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
      - GF_INSTALL_PLUGINS=grafana-clickhouse-datasource
      - GF_CLICKHOUSE_USER=${CLICKHOUSE_USER}
      - GF_CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning

volumes:
  clickhouse-data:
    name: clickhouse-data
  postgres-data:
    name: postgres-data
  grafana-data:
    name: grafana-data
